import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    dashboard: 'Dashboard',
    products: 'Products',
    scanner: 'Scanner',
    barcodes: 'Barcodes',
    users: 'Users',
    signOut: 'Sign out',
    lastUpdated: 'Last updated',
    totalProducts: 'Products',
    totalVariants: 'Variants',
    totalUnits: 'Total units',
    stockValue: 'Stock value',
    lowStock: 'Low stock',
    recentScans: 'Recent scans',
    allWellStocked: 'All products well stocked.',
    noScans: 'No scans recorded yet.',
    customThresholds: 'custom thresholds',
    loading: 'Loading...',
    addProduct: '+ Add product',
    cancel: 'Cancel',
    exportCSV: 'Export CSV',
    exportLoyverseCSV: 'Loyverse CSV',
    searchPlaceholder: 'Search by name, color, barcode...',
    allCategories: 'All categories',
    clear: 'Clear',
    newProduct: 'New product',
    name: 'Name',
    category: 'Category',
    costPrice: 'Cost price (€)',
    sellingPrice: 'Selling price (€)',
    lowStockAlert: 'Low stock alert',
    alertWhenStock: 'Alert when stock falls at or below',
    units: 'units',
    imageUrl: 'Image URL',
    notes: 'Notes',
    variants: 'Variants',
    color: 'Color',
    size: 'Size',
    initialQty: 'Initial qty',
    addVariant: 'Add variant',
    generate4: '+ Generate 4 sizes',
    generate5: '+ Generate 5 sizes',
    saveProduct: 'Save product',
    saving: 'Saving...',
    noProducts: 'No products yet. Add your first one above.',
    noMatch: 'No products match your search.',
    of: 'of',
    product: 'product',
    products2: 'products',
    cost: 'cost',
    sell: 'sell',
    alertAt: 'alert at ≤',
    duplicate: 'Duplicate',
    duplicating: 'Duplicating...',
    delete: 'Delete',
    history: 'History',
    remove: 'Remove',
    colorCol: 'Color',
    sizeCol: 'Size',
    barcodeId: 'Barcode ID',
    stock: 'Stock',
    receive: 'Receive',
    sellMode: 'Sell',
    scanReceiveHint: 'Scan a barcode to add +1 to stock',
    scanSellHint: 'Scan a barcode to remove -1 from stock (sale)',
    scanPlaceholder: 'Scan / enter barcode...',
    sessionLog: 'Session log',
    selectProduct: 'Select product',
    printAll: 'Print all',
    allVariants: 'all variants',
    print: 'Print',
    addUser: '+ Add user',
    newUser: 'New user',
    username: 'Username',
    password: 'Password',
    role: 'Role',
    createUser: 'Create user',
    creating: 'Creating...',
    usernameCol: 'Username',
    roleCol: 'Role',
    created: 'Created',
    noUsers: 'No users found.',
    stockHistory: 'Stock history',
    noMovements: 'No movements recorded yet.',
    currentStock: 'Current stock',
    deleteProduct: 'Delete this product and all its variants? This cannot be undone.',
    deleteUser: 'They will no longer be able to sign in.',
    productSaved: 'Product saved successfully.',
    productDeleted: 'Product deleted.',
    productDuplicated: 'Product duplicated.',
    userCreated: 'User created.',
    userDeleted: 'User deleted.',
    failedSave: 'Failed to save product.',
    failedDuplicate: 'Failed to duplicate product.',
    invalidLogin: 'Invalid username or password.',
    language: 'Language',
    english: 'English',
    turkish: 'Turkish',
  },
  tr: {
    dashboard: 'Gösterge Paneli',
    products: 'Ürünler',
    scanner: 'Tarayıcı',
    barcodes: 'Barkodlar',
    users: 'Kullanıcılar',
    signOut: 'Çıkış Yap',
    lastUpdated: 'Son güncelleme',
    totalProducts: 'Ürünler',
    totalVariants: 'Varyantlar',
    totalUnits: 'Toplam adet',
    stockValue: 'Stok değeri',
    lowStock: 'Düşük stok',
    recentScans: 'Son taramalar',
    allWellStocked: 'Tüm ürünler yeterli stokta.',
    noScans: 'Henüz tarama kaydı yok.',
    customThresholds: 'özel eşikler',
    loading: 'Yükleniyor...',
    addProduct: '+ Ürün ekle',
    cancel: 'İptal',
    exportCSV: 'CSV İndir',
    exportLoyverseCSV: 'Loyverse CSV',
    searchPlaceholder: 'İsim, renk, barkod ile ara...',
    allCategories: 'Tüm kategoriler',
    clear: 'Temizle',
    newProduct: 'Yeni ürün',
    name: 'İsim',
    category: 'Kategori',
    costPrice: 'Maliyet fiyatı (€)',
    sellingPrice: 'Satış fiyatı (€)',
    lowStockAlert: 'Düşük stok uyarısı',
    alertWhenStock: 'Stok şu değere düşünce uyar',
    units: 'adet',
    imageUrl: 'Resim URL',
    notes: 'Notlar',
    variants: 'Varyantlar',
    color: 'Renk',
    size: 'Beden',
    initialQty: 'Başlangıç adedi',
    addVariant: 'Varyant ekle',
    generate4: '+ 4 beden oluştur',
    generate5: '+ 5 beden oluştur',
    saveProduct: 'Ürünü kaydet',
    saving: 'Kaydediliyor...',
    noProducts: 'Henüz ürün yok. İlk ürününüzü ekleyin.',
    noMatch: 'Aramanızla eşleşen ürün yok.',
    of: '/',
    product: 'ürün',
    products2: 'ürün',
    cost: 'maliyet',
    sell: 'satış',
    alertAt: 'uyarı ≤',
    duplicate: 'Kopyala',
    duplicating: 'Kopyalanıyor...',
    delete: 'Sil',
    history: 'Geçmiş',
    remove: 'Kaldır',
    colorCol: 'Renk',
    sizeCol: 'Beden',
    barcodeId: 'Barkod NO',
    stock: 'Stok',
    receive: 'Giriş',
    sellMode: 'Satış',
    scanReceiveHint: 'Stoğa +1 eklemek için barkod tarayın',
    scanSellHint: 'Satış için stoktan -1 düşmek için barkod tarayın',
    scanPlaceholder: 'Barkod tara / gir...',
    sessionLog: 'Oturum günlüğü',
    selectProduct: 'Ürün seçin',
    printAll: 'Tümünü yazdır',
    allVariants: 'tüm varyantlar',
    print: 'Yazdır',
    addUser: '+ Kullanıcı ekle',
    newUser: 'Yeni kullanıcı',
    username: 'Kullanıcı adı',
    password: 'Şifre',
    role: 'Rol',
    createUser: 'Kullanıcı oluştur',
    creating: 'Oluşturuluyor...',
    usernameCol: 'Kullanıcı adı',
    roleCol: 'Rol',
    created: 'Oluşturuldu',
    noUsers: 'Kullanıcı bulunamadı.',
    stockHistory: 'Stok geçmişi',
    noMovements: 'Henüz hareket kaydı yok.',
    currentStock: 'Mevcut stok',
    deleteProduct: 'Bu ürün ve tüm varyantları silinsin mi? Bu işlem geri alınamaz.',
    deleteUser: 'Kullanıcı artık giriş yapamayacak.',
    productSaved: 'Ürün başarıyla kaydedildi.',
    productDeleted: 'Ürün silindi.',
    productDuplicated: 'Ürün kopyalandı.',
    userCreated: 'Kullanıcı oluşturuldu.',
    userDeleted: 'Kullanıcı silindi.',
    failedSave: 'Ürün kaydedilemedi.',
    failedDuplicate: 'Ürün kopyalanamadı.',
    invalidLogin: 'Geçersiz kullanıcı adı veya şifre.',
    language: 'Dil',
    english: 'İngilizce',
    turkish: 'Türkçe',
  }
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('language') || 'en')

  function t(key) {
    return translations[lang][key] || translations['en'][key] || key
  }

  function switchLanguage(newLang) {
    setLang(newLang)
    localStorage.setItem('language', newLang)
    client.patch('/auth/language', { language: newLang }).catch(() => {})
  }

  return (
    <LanguageContext.Provider value={{ lang, t, switchLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}